/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as RolesIndexRouteImport } from './routes/roles.index'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as RolesSlugRouteImport } from './routes/roles.$slug'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRoute,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RolesRoute,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SkillsRoute,
} as any)
const RolesSlugRoute = RolesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RolesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/roles': typeof RolesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/upload': typeof UploadRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/roles/': typeof RolesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/roles': typeof RolesIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/roles': typeof RolesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/upload': typeof UploadRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/roles/': typeof RolesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/roles'
    | '/search'
    | '/settings'
    | '/skills'
    | '/upload'
    | '/roles/$slug'
    | '/skills/$slug'
    | '/roles/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/upload'
    | '/roles/$slug'
    | '/skills/$slug'
    | '/roles'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/roles'
    | '/search'
    | '/settings'
    | '/skills'
    | '/upload'
    | '/roles/$slug'
    | '/skills/$slug'
    | '/roles/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RolesRoute: typeof RolesRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/roles/': {
      id: '/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof RolesRoute
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/roles/$slug': {
      id: '/roles/$slug'
      path: '/$slug'
      fullPath: '/roles/$slug'
      preLoaderRoute: typeof RolesSlugRouteImport
      parentRoute: typeof RolesRoute
    }
  }
}

interface RolesRouteChildren {
  RolesSlugRoute: typeof RolesSlugRoute
  RolesIndexRoute: typeof RolesIndexRoute
}

const RolesRouteChildren: RolesRouteChildren = {
  RolesSlugRoute: RolesSlugRoute,
  RolesIndexRoute: RolesIndexRoute,
}

const RolesRouteWithChildren = RolesRoute._addFileChildren(RolesRouteChildren)

interface SkillsRouteChildren {
  SkillsSlugRoute: typeof SkillsSlugRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSlugRoute: SkillsSlugRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RolesRoute: RolesRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRouteWithChildren,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
