/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScanQueueRouteImport } from './routes/scan-queue'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as RolesIndexRouteImport } from './routes/roles.index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as RolesSlugRouteImport } from './routes/roles.$slug'
import { Route as MemoriesSlugRouteImport } from './routes/memories.$slug'
import { Route as IntegrationsSlugRouteImport } from './routes/integrations.$slug'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanQueueRoute = ScanQueueRouteImport.update({
  id: '/scan-queue',
  path: '/scan-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRoute,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RolesRoute,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoriesRoute,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SkillsRoute,
} as any)
const RolesSlugRoute = RolesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RolesRoute,
} as any)
const MemoriesSlugRoute = MemoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MemoriesRoute,
} as any)
const IntegrationsSlugRoute = IntegrationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IntegrationsRoute,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/memories': typeof MemoriesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRouteWithChildren
  '/scan-queue': typeof ScanQueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/memories/$slug': typeof MemoriesSlugRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/scan-queue': typeof ScanQueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/memories/$slug': typeof MemoriesSlugRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/agents': typeof AgentsIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/roles': typeof RolesIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/memories': typeof MemoriesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRouteWithChildren
  '/scan-queue': typeof ScanQueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/users': typeof UsersRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/memories/$slug': typeof MemoriesSlugRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/integrations'
    | '/memories'
    | '/reports'
    | '/roles'
    | '/scan-queue'
    | '/search'
    | '/settings'
    | '/skills'
    | '/stars'
    | '/upload'
    | '/users'
    | '/agents/$slug'
    | '/integrations/$slug'
    | '/memories/$slug'
    | '/roles/$slug'
    | '/skills/$slug'
    | '/agents/'
    | '/integrations/'
    | '/memories/'
    | '/roles/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reports'
    | '/scan-queue'
    | '/search'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/users'
    | '/agents/$slug'
    | '/integrations/$slug'
    | '/memories/$slug'
    | '/roles/$slug'
    | '/skills/$slug'
    | '/agents'
    | '/integrations'
    | '/memories'
    | '/roles'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/dashboard'
    | '/integrations'
    | '/memories'
    | '/reports'
    | '/roles'
    | '/scan-queue'
    | '/search'
    | '/settings'
    | '/skills'
    | '/stars'
    | '/upload'
    | '/users'
    | '/agents/$slug'
    | '/integrations/$slug'
    | '/memories/$slug'
    | '/roles/$slug'
    | '/skills/$slug'
    | '/agents/'
    | '/integrations/'
    | '/memories/'
    | '/roles/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  MemoriesRoute: typeof MemoriesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRouteWithChildren
  ScanQueueRoute: typeof ScanQueueRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  StarsRoute: typeof StarsRoute
  UploadRoute: typeof UploadRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-queue': {
      id: '/scan-queue'
      path: '/scan-queue'
      fullPath: '/scan-queue'
      preLoaderRoute: typeof ScanQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/roles/': {
      id: '/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof RolesRoute
    }
    '/memories/': {
      id: '/memories/'
      path: '/'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/roles/$slug': {
      id: '/roles/$slug'
      path: '/$slug'
      fullPath: '/roles/$slug'
      preLoaderRoute: typeof RolesSlugRouteImport
      parentRoute: typeof RolesRoute
    }
    '/memories/$slug': {
      id: '/memories/$slug'
      path: '/$slug'
      fullPath: '/memories/$slug'
      preLoaderRoute: typeof MemoriesSlugRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/integrations/$slug': {
      id: '/integrations/$slug'
      path: '/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof IntegrationsSlugRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsSlugRoute: typeof AgentsSlugRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsSlugRoute: AgentsSlugRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsSlugRoute: typeof IntegrationsSlugRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsSlugRoute: IntegrationsSlugRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface MemoriesRouteChildren {
  MemoriesSlugRoute: typeof MemoriesSlugRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

const MemoriesRouteChildren: MemoriesRouteChildren = {
  MemoriesSlugRoute: MemoriesSlugRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}

const MemoriesRouteWithChildren = MemoriesRoute._addFileChildren(
  MemoriesRouteChildren,
)

interface RolesRouteChildren {
  RolesSlugRoute: typeof RolesSlugRoute
  RolesIndexRoute: typeof RolesIndexRoute
}

const RolesRouteChildren: RolesRouteChildren = {
  RolesSlugRoute: RolesSlugRoute,
  RolesIndexRoute: RolesIndexRoute,
}

const RolesRouteWithChildren = RolesRoute._addFileChildren(RolesRouteChildren)

interface SkillsRouteChildren {
  SkillsSlugRoute: typeof SkillsSlugRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSlugRoute: SkillsSlugRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  MemoriesRoute: MemoriesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRouteWithChildren,
  ScanQueueRoute: ScanQueueRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRouteWithChildren,
  StarsRoute: StarsRoute,
  UploadRoute: UploadRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
